// Generated by BuildLang Compiler
// Do not edit manually

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


// ============================================================================
// BuildLang Runtime Library
// Embedded in generated C output - do not edit
// ============================================================================

// --- String type ---

typedef struct {
    const char* ptr;
    size_t len;
    size_t cap;    // 0 for string literals (not heap-allocated)
} BuildString;

static BuildString build_string_new(const char* s) {
    BuildString qs;
    qs.ptr = s;
    qs.len = strlen(s);
    qs.cap = 0; // literal, not owned
    return qs;
}

static BuildString build_string_concat(BuildString a, BuildString b) {
    size_t new_len = a.len + b.len;
    char* buf = (char*)malloc(new_len + 1);
    memcpy(buf, a.ptr, a.len);
    memcpy(buf + a.len, b.ptr, b.len);
    buf[new_len] = '\0';
    BuildString qs;
    qs.ptr = buf;
    qs.len = new_len;
    qs.cap = new_len + 1;
    return qs;
}

static size_t build_string_len(BuildString s) {
    return s.len;
}

static bool build_string_eq(BuildString a, BuildString b) {
    if (a.len != b.len) return false;
    return memcmp(a.ptr, b.ptr, a.len) == 0;
}

static void build_string_free(BuildString s) {
    if (s.cap > 0) free((void*)s.ptr);
}

// --- Vec (dynamic array) type ---

typedef struct {
    void* ptr;
    size_t len;
    size_t cap;
    size_t elem_size;
} BuildVec;

static BuildVec build_vec_new(size_t elem_size) {
    BuildVec v;
    v.ptr = NULL;
    v.len = 0;
    v.cap = 0;
    v.elem_size = elem_size;
    return v;
}

static void build_vec_push(BuildVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->ptr = realloc(v->ptr, v->cap * v->elem_size);
    }
    memcpy((char*)v->ptr + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* build_vec_get(BuildVec* v, size_t index) {
    return (char*)v->ptr + index * v->elem_size;
}

static void build_vec_free(BuildVec* v) {
    free(v->ptr);
    v->ptr = NULL;
    v->len = 0;
    v->cap = 0;
}

// --- Print formatting helpers ---

static void build_print_i32(int32_t v) { printf("%d", v); }
static void build_print_i64(int64_t v) { printf("%lld", (long long)v); }
static void build_print_f32(float v) { printf("%g", (double)v); }
static void build_print_f64(double v) { printf("%g", v); }
static void build_print_bool(bool v) { printf("%s", v ? "true" : "false"); }
static void build_print_str(const char* v) { printf("%s", v); }
static void build_print_string(BuildString v) { printf("%.*s", (int)v.len, v.ptr); }
static void build_print_char(char v) { printf("%c", v); }

// --- Math built-in helpers ---

static int32_t build_min_i32(int32_t a, int32_t b) { return a < b ? a : b; }
static int32_t build_max_i32(int32_t a, int32_t b) { return a > b ? a : b; }
static int64_t build_min_i64(int64_t a, int64_t b) { return a < b ? a : b; }
static int64_t build_max_i64(int64_t a, int64_t b) { return a > b ? a : b; }
static double build_min_f64(double a, double b) { return a < b ? a : b; }
static double build_max_f64(double a, double b) { return a > b ? a : b; }
static float build_min_f32(float a, float b) { return a < b ? a : b; }
static float build_max_f32(float a, float b) { return a > b ? a : b; }

// --- Vector Math Types ---

typedef struct { double x, y; } build_vec2;
typedef struct { double x, y, z; } build_vec3;
typedef struct { double x, y, z, w; } build_vec4;
typedef struct { double m[4][4]; } build_mat4;

// Constructors
static build_vec2 build_vec2_new(double x, double y) { return (build_vec2){x, y}; }
static build_vec3 build_vec3_new(double x, double y, double z) { return (build_vec3){x, y, z}; }
static build_vec4 build_vec4_new(double x, double y, double z, double w) { return (build_vec4){x, y, z, w}; }

// Vector dot product
static double build_dot2(build_vec2 a, build_vec2 b) { return a.x*b.x + a.y*b.y; }
static double build_dot3(build_vec3 a, build_vec3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }
static double build_dot4(build_vec4 a, build_vec4 b) { return a.x*b.x + a.y*b.y + a.z*b.z + a.w*b.w; }

// Vector length
static double build_length2(build_vec2 v) { return sqrt(build_dot2(v, v)); }
static double build_length3(build_vec3 v) { return sqrt(build_dot3(v, v)); }
static double build_length4(build_vec4 v) { return sqrt(build_dot4(v, v)); }

// Vector normalize
static build_vec2 build_normalize2(build_vec2 v) { double l = build_length2(v); return (build_vec2){v.x/l, v.y/l}; }
static build_vec3 build_normalize3(build_vec3 v) { double l = build_length3(v); return (build_vec3){v.x/l, v.y/l, v.z/l}; }
static build_vec4 build_normalize4(build_vec4 v) { double l = build_length4(v); return (build_vec4){v.x/l, v.y/l, v.z/l, v.w/l}; }

// Cross product (vec3 only)
static build_vec3 build_cross(build_vec3 a, build_vec3 b) {
    return (build_vec3){a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x};
}

// Reflect
static build_vec3 build_reflect3(build_vec3 v, build_vec3 n) {
    double d = build_dot3(v, n);
    return (build_vec3){v.x - 2.0*d*n.x, v.y - 2.0*d*n.y, v.z - 2.0*d*n.z};
}

// Lerp
static build_vec2 build_lerp2(build_vec2 a, build_vec2 b, double t) {
    return (build_vec2){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t};
}
static build_vec3 build_lerp3(build_vec3 a, build_vec3 b, double t) {
    return (build_vec3){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t};
}
static build_vec4 build_lerp4(build_vec4 a, build_vec4 b, double t) {
    return (build_vec4){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t, a.w + (b.w-a.w)*t};
}

// Vec2 arithmetic
static build_vec2 build_vec2_add(build_vec2 a, build_vec2 b) { return (build_vec2){a.x+b.x, a.y+b.y}; }
static build_vec2 build_vec2_sub(build_vec2 a, build_vec2 b) { return (build_vec2){a.x-b.x, a.y-b.y}; }
static build_vec2 build_vec2_mul(build_vec2 a, build_vec2 b) { return (build_vec2){a.x*b.x, a.y*b.y}; }
static build_vec2 build_vec2_scale(build_vec2 v, double s) { return (build_vec2){v.x*s, v.y*s}; }
static build_vec2 build_vec2_neg(build_vec2 v) { return (build_vec2){-v.x, -v.y}; }

// Vec3 arithmetic
static build_vec3 build_vec3_add(build_vec3 a, build_vec3 b) { return (build_vec3){a.x+b.x, a.y+b.y, a.z+b.z}; }
static build_vec3 build_vec3_sub(build_vec3 a, build_vec3 b) { return (build_vec3){a.x-b.x, a.y-b.y, a.z-b.z}; }
static build_vec3 build_vec3_mul(build_vec3 a, build_vec3 b) { return (build_vec3){a.x*b.x, a.y*b.y, a.z*b.z}; }
static build_vec3 build_vec3_scale(build_vec3 v, double s) { return (build_vec3){v.x*s, v.y*s, v.z*s}; }
static build_vec3 build_vec3_neg(build_vec3 v) { return (build_vec3){-v.x, -v.y, -v.z}; }

// Vec4 arithmetic
static build_vec4 build_vec4_add(build_vec4 a, build_vec4 b) { return (build_vec4){a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w}; }
static build_vec4 build_vec4_sub(build_vec4 a, build_vec4 b) { return (build_vec4){a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w}; }
static build_vec4 build_vec4_mul(build_vec4 a, build_vec4 b) { return (build_vec4){a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w}; }
static build_vec4 build_vec4_scale(build_vec4 v, double s) { return (build_vec4){v.x*s, v.y*s, v.z*s, v.w*s}; }
static build_vec4 build_vec4_neg(build_vec4 v) { return (build_vec4){-v.x, -v.y, -v.z, -v.w}; }

// --- Mat4 operations ---

static build_mat4 build_mat4_identity(void) {
    build_mat4 m = {{{1,0,0,0},{0,1,0,0},{0,0,1,0},{0,0,0,1}}};
    return m;
}

static build_mat4 build_mat4_mul(build_mat4 a, build_mat4 b) {
    build_mat4 r = {{{0}}};
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            for (int k = 0; k < 4; k++)
                r.m[i][j] += a.m[i][k] * b.m[k][j];
    return r;
}

static build_vec4 build_mat4_mul_vec4(build_mat4 m, build_vec4 v) {
    return (build_vec4){
        m.m[0][0]*v.x + m.m[0][1]*v.y + m.m[0][2]*v.z + m.m[0][3]*v.w,
        m.m[1][0]*v.x + m.m[1][1]*v.y + m.m[1][2]*v.z + m.m[1][3]*v.w,
        m.m[2][0]*v.x + m.m[2][1]*v.y + m.m[2][2]*v.z + m.m[2][3]*v.w,
        m.m[3][0]*v.x + m.m[3][1]*v.y + m.m[3][2]*v.z + m.m[3][3]*v.w
    };
}

static build_mat4 build_mat4_translate(build_vec3 t) {
    build_mat4 m = build_mat4_identity();
    m.m[0][3] = t.x; m.m[1][3] = t.y; m.m[2][3] = t.z;
    return m;
}

static build_mat4 build_mat4_scale(build_vec3 s) {
    build_mat4 m = {{{s.x,0,0,0},{0,s.y,0,0},{0,0,s.z,0},{0,0,0,1}}};
    return m;
}

static build_mat4 build_mat4_perspective(double fov, double aspect, double near_val, double far_val) {
    double f = 1.0 / tan(fov * 0.5);
    build_mat4 m = {{{0}}};
    m.m[0][0] = f / aspect;
    m.m[1][1] = f;
    m.m[2][2] = (far_val + near_val) / (near_val - far_val);
    m.m[2][3] = (2.0 * far_val * near_val) / (near_val - far_val);
    m.m[3][2] = -1.0;
    return m;
}

// --- Shader math functions ---

static double build_clampf(double x, double lo, double hi) { return x < lo ? lo : (x > hi ? hi : x); }
static build_vec3 build_clamp3(build_vec3 v, double lo, double hi) {
    return (build_vec3){build_clampf(v.x, lo, hi), build_clampf(v.y, lo, hi), build_clampf(v.z, lo, hi)};
}
static double build_smoothstep(double edge0, double edge1, double x) {
    double t = build_clampf((x - edge0) / (edge1 - edge0), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}
static double build_mix(double a, double b, double t) { return a + (b - a) * t; }
static double build_fract(double x) { return x - floor(x); }
static double build_step(double edge, double x) { return x < edge ? 0.0 : 1.0; }

// --- Effect handler runtime (setjmp/longjmp based) ---

#include <setjmp.h>

// Effect handler stack
typedef struct BuildHandler {
    jmp_buf env;
    int32_t effect_id;
    void* handler_data;
    struct BuildHandler* parent;
} BuildHandler;

// Global handler stack
static BuildHandler* __build_handler_stack = NULL;

// Push a handler onto the stack
static void build_push_handler(BuildHandler* h, int32_t effect_id) {
    h->effect_id = effect_id;
    h->handler_data = NULL;
    h->parent = __build_handler_stack;
    __build_handler_stack = h;
}

// Pop a handler from the stack
static void build_pop_handler(void) {
    if (__build_handler_stack) {
        __build_handler_stack = __build_handler_stack->parent;
    }
}

// Perform an effect operation - jumps to the nearest handler
static void build_perform(int32_t effect_id, int32_t op_id, void* arg, void* result) {
    BuildHandler* h = __build_handler_stack;
    while (h) {
        if (h->effect_id == effect_id) {
            h->handler_data = arg;
            longjmp(h->env, op_id + 1); // +1 because setjmp returns 0 on first call
        }
        h = h->parent;
    }
    // Unhandled effect - abort
    fprintf(stderr, "Unhandled effect %d operation %d\n", effect_id, op_id);
    abort();
}

// --- File I/O ---

static BuildString build_read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return build_string_new("");
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    BuildString qs;
    qs.ptr = buf;
    qs.len = (size_t)len;
    qs.cap = (size_t)(len + 1);
    return qs;
}

static bool build_write_file(const char* path, const char* content) {
    FILE* f = fopen(path, "wb");
    if (!f) return false;
    size_t len = strlen(content);
    size_t written = fwrite(content, 1, len, f);
    fclose(f);
    return written == len;
}

static bool build_file_exists(const char* path) {
    FILE* f = fopen(path, "rb");
    if (f) { fclose(f); return true; }
    return false;
}

// --- Process / Environment ---

static int32_t build_exit(int32_t code) {
    exit(code);
    return code; // unreachable
}

// --- Graphics Stub (Vulkan helper) ---
// Minimal stub that prints what a real Vulkan backend would do.
// Used for testing the FFI integration pattern.
// When connected to a real Vulkan backend, these are replaced by
// linking against vulkan_helper.c / the Vulkan SDK.

typedef struct {
    int32_t initialized;
    int32_t width;
    int32_t height;
    int32_t frame_count;
    int32_t should_close;
} BuildGfxContext;

static BuildGfxContext __build_gfx_ctx = {0, 0, 0, 0, 0};

static int32_t build_gfx_init(int32_t width, int32_t height, const char* title) {
    printf("[GFX] Initializing %dx%d window: %s\n", width, height, title);
    __build_gfx_ctx.initialized = 1;
    __build_gfx_ctx.width = width;
    __build_gfx_ctx.height = height;
    __build_gfx_ctx.frame_count = 0;
    __build_gfx_ctx.should_close = 0;
    printf("[GFX] Vulkan instance created\n");
    printf("[GFX] Physical device selected\n");
    printf("[GFX] Logical device created\n");
    printf("[GFX] Swapchain created (%dx%d)\n", width, height);
    return 1;
}

static int32_t build_gfx_load_shader(const char* path, int32_t stage) {
    printf("[GFX] Loading shader: %s (stage=%s)\n", path, stage == 0 ? "vertex" : "fragment");
    return 1;
}

static int32_t build_gfx_create_pipeline(int32_t vertex_shader, int32_t fragment_shader) {
    printf("[GFX] Creating graphics pipeline (vs=%d, fs=%d)\n", vertex_shader, fragment_shader);
    return 1;
}

static void build_gfx_begin_frame(void) {
    __build_gfx_ctx.frame_count++;
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Begin frame %d\n", __build_gfx_ctx.frame_count);
    }
}

static void build_gfx_clear(float r, float g, float b, float a) {
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Clear (%.1f, %.1f, %.1f, %.1f)\n", r, g, b, a);
    }
}

static void build_gfx_draw(int32_t vertex_count) {
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Draw %d vertices\n", vertex_count);
    }
}

static void build_gfx_end_frame(void) {
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] End frame %d\n", __build_gfx_ctx.frame_count);
    }
    if (__build_gfx_ctx.frame_count >= 3) {
        __build_gfx_ctx.should_close = 1;
    }
}

static int32_t build_gfx_should_close(void) {
    return __build_gfx_ctx.should_close;
}

static void build_gfx_shutdown(void) {
    printf("[GFX] Shutdown complete (%d frames rendered)\n", __build_gfx_ctx.frame_count);
    __build_gfx_ctx.initialized = 0;
}

// ============================================================================
// End BuildLang Runtime
// ============================================================================

// Type definitions
// String table
static const char* __str0 = "=== Volumetric Fog Ray Marching ===\n";
static const char* __str1 = "\n";
static const char* __str2 = "Beer-Lambert (d=0.1, dist=10): %g (expect ~0.37)\n";
static const char* __str3 = "Beer-Lambert (d=0.5, dist=10): %g (expect ~0.007)\n";
static const char* __str4 = "HG forward (g=0.7):  %g (should be high)\n";
static const char* __str5 = "HG backward (g=0.7): %g (should be low)\n";
static const char* __str6 = "HG isotropic (g=0):  %g (expect ~0.08)\n";
static const char* __str7 = "Fog at ground: %g (expect 0.1)\n";
static const char* __str8 = "Fog at y=10:   %g (expect ~0.0067)\n";
static const char* __str9 = "Fog (toward sun): %g (forward scattering)\n";
static const char* __str10 = "Fog (away from sun): %g (less scattering)\n";
static const char* __str11 = "=== Same shader compiles to Vulkan 1.0 SPIR-V ===\n";

// Forward declarations
static double pi(void);
static double beer_lambert(double density, double distance);
static double henyey_greenstein(double cos_theta, double g);
static double height_fog_density(double y, double base_density, double falloff);
static double raymarch_fog(double ray_start_y, double ray_end_y, double ray_length, double light_cos_angle, double base_density, double falloff, double scatter_g, int32_t num_steps);
static double aces(double x);
static build_vec4 fs_fog(build_vec3 ray_params);
int32_t main(void);

static double pi(void) {
    double _ret;

    return 3.14159265358979;
}

static double beer_lambert(double density, double distance) {
    double _ret;
    double _3;
    double _4;
    double _5;

    _3 = (density * distance);
    _4 = (0 - _3);
    _5 = pow(2.718281828, _4);
    goto bb1;
bb1:
    return _5;
}

static double henyey_greenstein(double cos_theta, double g) {
    double _ret;
    double _3;
    double g2;
    double _5;
    double _6;
    double _7;
    double _8;
    double denom;
    double _10;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;

    _3 = (g * g);
    g2 = _3;
    _5 = (1 + g2);
    _6 = (2 * g);
    _7 = (_6 * cos_theta);
    _8 = (_5 - _7);
    denom = _8;
    _10 = (1 - g2);
    _11 = pi();
    goto bb1;
bb1:
    _12 = (4 * _11);
    _13 = pow(denom, 1.5);
    goto bb2;
bb2:
    _14 = (_12 * _13);
    _15 = (_10 / _14);
    return _15;
}

static double height_fog_density(double y, double base_density, double falloff) {
    double _ret;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;

    _4 = build_clampf(y, 0, 100);
    goto bb1;
bb1:
    _5 = (falloff * _4);
    _6 = (0 - _5);
    _7 = pow(2.718281828, _6);
    goto bb2;
bb2:
    _8 = (base_density * _7);
    return _8;
}

static double raymarch_fog(double ray_start_y, double ray_end_y, double ray_length, double light_cos_angle, double base_density, double falloff, double scatter_g, int32_t num_steps) {
    double _ret;
    double _9;
    double step_size;
    double total_transmittance;
    double in_scatter;
    int32_t i;
    bool _14;
    double _15;
    double _16;
    double _17;
    double t;
    double _19;
    double _20;
    double _21;
    double sample_y;
    double _23;
    double density;
    double _25;
    double step_extinction;
    double _27;
    double phase;
    double _29;
    double _30;
    double _31;
    double _32;
    double _33;
    int32_t _34;

    _9 = (ray_length / 16);
    step_size = _9;
    total_transmittance = 1;
    in_scatter = 0;
    i = 0;
    goto bb1;
bb1:
    _14 = (i < 16);
    if (_14) goto bb2; else goto bb3;
bb2:
    _15 = ((double)i);
    _16 = (_15 + 0.5);
    _17 = (_16 / 16);
    t = _17;
    _19 = (ray_end_y - ray_start_y);
    _20 = (_19 * t);
    _21 = (ray_start_y + _20);
    sample_y = _21;
    _23 = height_fog_density(sample_y, base_density, falloff);
    goto bb4;
bb3:
    return in_scatter;
bb4:
    density = _23;
    _25 = beer_lambert(density, step_size);
    goto bb5;
bb5:
    step_extinction = _25;
    _27 = henyey_greenstein(light_cos_angle, scatter_g);
    goto bb6;
bb6:
    phase = _27;
    _29 = (total_transmittance * density);
    _30 = (_29 * phase);
    _31 = (_30 * step_size);
    _32 = (in_scatter + _31);
    in_scatter = _32;
    _33 = (total_transmittance * step_extinction);
    total_transmittance = _33;
    _34 = (i + 1);
    i = _34;
    goto bb1;
}

static double aces(double x) {
    double _ret;
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;

    _2 = (2.51 * x);
    _3 = (_2 + 0.03);
    _4 = (x * _3);
    _5 = (2.43 * x);
    _6 = (_5 + 0.59);
    _7 = (x * _6);
    _8 = (_7 + 0.14);
    _9 = (_4 / _8);
    _10 = build_clampf(_9, 0, 1);
    goto bb1;
bb1:
    return _10;
}

static build_vec4 fs_fog(build_vec3 ray_params) {
    build_vec4 _ret;
    double _2;
    double _3;
    double _4;
    double _5;
    double fog;
    double _7;
    double _8;
    double mapped;
    build_vec4 _10;

    _2 = ray_params.x;
    _3 = ray_params.y;
    _4 = ray_params.z;
    _5 = raymarch_fog(_2, _3, 50, _4, 0.05, 0.1, 0.7, 16);
    goto bb1;
bb1:
    fog = _5;
    _7 = (fog * 5);
    _8 = aces(_7);
    goto bb2;
bb2:
    mapped = _8;
    _10 = (build_vec4){ mapped, mapped, mapped, 1 };
    return _10;
}

int32_t main(void) {
    int32_t _ret;
    int8_t* _1;
    int8_t* _2;
    double _3;
    double t1;
    int8_t* _5;
    double _6;
    double t2;
    int8_t* _8;
    double _9;
    double p_forward;
    double _11;
    double _12;
    double p_back;
    double _14;
    double p_iso;
    int8_t* _16;
    int8_t* _17;
    int8_t* _18;
    double _19;
    double d_ground;
    double _21;
    double d_high;
    int8_t* _23;
    int8_t* _24;
    double _25;
    double fog_toward_sun;
    int8_t* _27;
    double _28;
    double _29;
    double fog_away;
    int8_t* _31;
    int8_t* _32;
    int8_t* _33;

    _1 = __str0;
    printf(_1);
    goto bb1;
bb1:
    _2 = __str1;
    printf(_2);
    goto bb2;
bb2:
    _3 = beer_lambert(0.1, 10);
    goto bb3;
bb3:
    t1 = _3;
    _5 = __str2;
    printf(_5, t1);
    goto bb4;
bb4:
    _6 = beer_lambert(0.5, 10);
    goto bb5;
bb5:
    t2 = _6;
    _8 = __str3;
    printf(_8, t2);
    goto bb6;
bb6:
    _9 = henyey_greenstein(1, 0.7);
    goto bb7;
bb7:
    p_forward = _9;
    _11 = (-1);
    _12 = henyey_greenstein(_11, 0.7);
    goto bb8;
bb8:
    p_back = _12;
    _14 = henyey_greenstein(0, 0);
    goto bb9;
bb9:
    p_iso = _14;
    _16 = __str4;
    printf(_16, p_forward);
    goto bb10;
bb10:
    _17 = __str5;
    printf(_17, p_back);
    goto bb11;
bb11:
    _18 = __str6;
    printf(_18, p_iso);
    goto bb12;
bb12:
    _19 = height_fog_density(0, 0.1, 0.5);
    goto bb13;
bb13:
    d_ground = _19;
    _21 = height_fog_density(10, 0.1, 0.5);
    goto bb14;
bb14:
    d_high = _21;
    _23 = __str7;
    printf(_23, d_ground);
    goto bb15;
bb15:
    _24 = __str8;
    printf(_24, d_high);
    goto bb16;
bb16:
    _25 = raymarch_fog(0, 5, 50, 0.9, 0.05, 0.1, 0.7, 16);
    goto bb17;
bb17:
    fog_toward_sun = _25;
    _27 = __str9;
    printf(_27, fog_toward_sun);
    goto bb18;
bb18:
    _28 = (-0.5);
    _29 = raymarch_fog(0, 5, 50, _28, 0.05, 0.1, 0.7, 16);
    goto bb19;
bb19:
    fog_away = _29;
    _31 = __str10;
    printf(_31, fog_away);
    goto bb20;
bb20:
    _32 = __str1;
    printf(_32);
    goto bb21;
bb21:
    _33 = __str11;
    printf(_33);
    goto bb22;
bb22:
    return 0;
}

