// Generated by BuildLang Compiler
// Do not edit manually

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


// ============================================================================
// BuildLang Runtime Library
// Embedded in generated C output - do not edit
// ============================================================================

// --- String type ---

typedef struct {
    const char* ptr;
    size_t len;
    size_t cap;    // 0 for string literals (not heap-allocated)
} BuildString;

static BuildString build_string_new(const char* s) {
    BuildString qs;
    qs.ptr = s;
    qs.len = strlen(s);
    qs.cap = 0; // literal, not owned
    return qs;
}

static BuildString build_string_concat(BuildString a, BuildString b) {
    size_t new_len = a.len + b.len;
    char* buf = (char*)malloc(new_len + 1);
    memcpy(buf, a.ptr, a.len);
    memcpy(buf + a.len, b.ptr, b.len);
    buf[new_len] = '\0';
    BuildString qs;
    qs.ptr = buf;
    qs.len = new_len;
    qs.cap = new_len + 1;
    return qs;
}

static size_t build_string_len(BuildString s) {
    return s.len;
}

static bool build_string_eq(BuildString a, BuildString b) {
    if (a.len != b.len) return false;
    return memcmp(a.ptr, b.ptr, a.len) == 0;
}

static void build_string_free(BuildString s) {
    if (s.cap > 0) free((void*)s.ptr);
}

// --- Vec (dynamic array) type ---

typedef struct {
    void* ptr;
    size_t len;
    size_t cap;
    size_t elem_size;
} BuildVec;

static BuildVec build_vec_new(size_t elem_size) {
    BuildVec v;
    v.ptr = NULL;
    v.len = 0;
    v.cap = 0;
    v.elem_size = elem_size;
    return v;
}

static void build_vec_push(BuildVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->ptr = realloc(v->ptr, v->cap * v->elem_size);
    }
    memcpy((char*)v->ptr + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* build_vec_get(BuildVec* v, size_t index) {
    return (char*)v->ptr + index * v->elem_size;
}

static void build_vec_free(BuildVec* v) {
    free(v->ptr);
    v->ptr = NULL;
    v->len = 0;
    v->cap = 0;
}

// --- Typed Vec helpers (wrapping BuildVec for specific element types) ---

static BuildVec build_vec_new_i32(void) { return build_vec_new(sizeof(int32_t)); }
static BuildVec build_vec_new_i64(void) { return build_vec_new(sizeof(int64_t)); }
static BuildVec build_vec_new_f64(void) { return build_vec_new(sizeof(double)); }

// Note: These wrappers use a global BuildVec pointer trick - the first
// argument is a BuildVec passed by value, but since BuildLang passes
// struct locals, the C compiler will place them on the stack where we
// can take their address. We use a thin wrapper to bridge the gap.
static BuildVec* __build_vec_ref = NULL;
static void build_vec_push_i32(BuildVec v, int32_t val) {
    // Find the original local via the stored pointer (set by codegen)
    // Fallback: push into a copy - but mutations won't be visible.
    // The real solution: codegen passes &v. For now we use a global registry.
    (void)v; (void)val;
}
// Simpler approach: heap-allocated vecs via a handle pattern
typedef struct { BuildVec* inner; } BuildVecHandle;

static BuildVecHandle build_hvec_new_i32(void) {
    BuildVecHandle h;
    h.inner = (BuildVec*)malloc(sizeof(BuildVec));
    *h.inner = build_vec_new(sizeof(int32_t));
    return h;
}
static void build_hvec_push_i32(BuildVecHandle h, int32_t val) { build_vec_push(h.inner, &val); }
static int32_t build_hvec_get_i32(BuildVecHandle h, size_t index) { return *(int32_t*)build_vec_get(h.inner, index); }
static size_t build_hvec_len(BuildVecHandle h) { return h.inner->len; }
static int32_t build_hvec_pop_i32(BuildVecHandle h) {
    if (h.inner->len == 0) return 0;
    h.inner->len--;
    return *(int32_t*)((char*)h.inner->ptr + h.inner->len * h.inner->elem_size);
}
static void build_hvec_free(BuildVecHandle h) { build_vec_free(h.inner); free(h.inner); }

// --- Format string helpers (returns BuildString) ---

static BuildString build_format_i32(const char* fmt, int32_t v) {
    char buf[64];
    int n = snprintf(buf, sizeof(buf), fmt, v);
    char* heap = (char*)malloc(n + 1);
    memcpy(heap, buf, n + 1);
    BuildString qs; qs.ptr = heap; qs.len = n; qs.cap = n + 1;
    return qs;
}

static BuildString build_format_f64(const char* fmt, double v) {
    char buf[128];
    int n = snprintf(buf, sizeof(buf), fmt, v);
    char* heap = (char*)malloc(n + 1);
    memcpy(heap, buf, n + 1);
    BuildString qs; qs.ptr = heap; qs.len = n; qs.cap = n + 1;
    return qs;
}

static BuildString build_format_str(const char* fmt, const char* v) {
    int n = snprintf(NULL, 0, fmt, v);
    char* heap = (char*)malloc(n + 1);
    snprintf(heap, n + 1, fmt, v);
    BuildString qs; qs.ptr = heap; qs.len = n; qs.cap = n + 1;
    return qs;
}

static BuildString build_i32_to_string(int32_t v) { return build_format_i32("%d", v); }
static BuildString build_f64_to_string(double v) { return build_format_f64("%g", v); }

// --- Math constants ---
static const double BUILD_PI = 3.14159265358979323846;
static const double BUILD_E = 2.71828182845904523536;
static const double BUILD_TAU = 6.28318530717958647692;

// --- HashMap (i32 -> i32, open addressing with linear probing) ---

typedef struct {
    int32_t* keys;
    int32_t* values;
    uint8_t* occupied;
    size_t cap;
    size_t len;
} BuildHashMap;

typedef struct { BuildHashMap* inner; } BuildMapHandle;

static BuildMapHandle build_map_new(void) {
    BuildMapHandle h;
    h.inner = (BuildHashMap*)malloc(sizeof(BuildHashMap));
    h.inner->cap = 16;
    h.inner->len = 0;
    h.inner->keys = (int32_t*)calloc(16, sizeof(int32_t));
    h.inner->values = (int32_t*)calloc(16, sizeof(int32_t));
    h.inner->occupied = (uint8_t*)calloc(16, sizeof(uint8_t));
    return h;
}

static void build_map_grow(BuildHashMap* m) {
    size_t old_cap = m->cap;
    int32_t* old_keys = m->keys;
    int32_t* old_values = m->values;
    uint8_t* old_occ = m->occupied;
    m->cap *= 2;
    m->len = 0;
    m->keys = (int32_t*)calloc(m->cap, sizeof(int32_t));
    m->values = (int32_t*)calloc(m->cap, sizeof(int32_t));
    m->occupied = (uint8_t*)calloc(m->cap, sizeof(uint8_t));
    for (size_t i = 0; i < old_cap; i++) {
        if (old_occ[i]) {
            uint32_t h = (uint32_t)old_keys[i] * 2654435761u;
            size_t idx = h % m->cap;
            while (m->occupied[idx]) idx = (idx + 1) % m->cap;
            m->keys[idx] = old_keys[i];
            m->values[idx] = old_values[i];
            m->occupied[idx] = 1;
            m->len++;
        }
    }
    free(old_keys); free(old_values); free(old_occ);
}

static void build_map_insert(BuildMapHandle h, int32_t key, int32_t value) {
    BuildHashMap* m = h.inner;
    if (m->len * 4 >= m->cap * 3) build_map_grow(m);
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) { m->values[idx] = value; return; }
        idx = (idx + 1) % m->cap;
    }
    m->keys[idx] = key;
    m->values[idx] = value;
    m->occupied[idx] = 1;
    m->len++;
}

static int32_t build_map_get(BuildMapHandle h, int32_t key, int32_t fallback) {
    BuildHashMap* m = h.inner;
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) return m->values[idx];
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return fallback;
}

static bool build_map_contains(BuildMapHandle h, int32_t key) {
    BuildHashMap* m = h.inner;
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) return true;
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

static size_t build_map_len(BuildMapHandle h) { return h.inner->len; }

static bool build_map_remove(BuildMapHandle h, int32_t key) {
    BuildHashMap* m = h.inner;
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) {
            m->occupied[idx] = 0;
            m->len--;
            return true;
        }
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

// --- Print formatting helpers ---

static void build_print_i32(int32_t v) { printf("%d", v); }
static void build_print_i64(int64_t v) { printf("%lld", (long long)v); }
static void build_print_f32(float v) { printf("%g", (double)v); }
static void build_print_f64(double v) { printf("%g", v); }
static void build_print_bool(bool v) { printf("%s", v ? "true" : "false"); }
static void build_print_str(const char* v) { printf("%s", v); }
static void build_print_string(BuildString v) { printf("%.*s", (int)v.len, v.ptr); }
static void build_print_char(char v) { printf("%c", v); }

// --- Math built-in helpers ---

static int32_t build_min_i32(int32_t a, int32_t b) { return a < b ? a : b; }
static int32_t build_max_i32(int32_t a, int32_t b) { return a > b ? a : b; }
static int64_t build_min_i64(int64_t a, int64_t b) { return a < b ? a : b; }
static int64_t build_max_i64(int64_t a, int64_t b) { return a > b ? a : b; }
static double build_min_f64(double a, double b) { return a < b ? a : b; }
static double build_max_f64(double a, double b) { return a > b ? a : b; }
static float build_min_f32(float a, float b) { return a < b ? a : b; }
static float build_max_f32(float a, float b) { return a > b ? a : b; }

// --- Vector Math Types ---

typedef struct { double x, y; } build_vec2;
typedef struct { double x, y, z; } build_vec3;
typedef struct { double x, y, z, w; } build_vec4;
typedef struct { double m[4][4]; } build_mat4;

// Constructors
static build_vec2 build_vec2_new(double x, double y) { return (build_vec2){x, y}; }
static build_vec3 build_vec3_new(double x, double y, double z) { return (build_vec3){x, y, z}; }
static build_vec4 build_vec4_new(double x, double y, double z, double w) { return (build_vec4){x, y, z, w}; }

// Vector dot product
static double build_dot2(build_vec2 a, build_vec2 b) { return a.x*b.x + a.y*b.y; }
static double build_dot3(build_vec3 a, build_vec3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }
static double build_dot4(build_vec4 a, build_vec4 b) { return a.x*b.x + a.y*b.y + a.z*b.z + a.w*b.w; }

// Vector length
static double build_length2(build_vec2 v) { return sqrt(build_dot2(v, v)); }
static double build_length3(build_vec3 v) { return sqrt(build_dot3(v, v)); }
static double build_length4(build_vec4 v) { return sqrt(build_dot4(v, v)); }

// Vector normalize
static build_vec2 build_normalize2(build_vec2 v) { double l = build_length2(v); return (build_vec2){v.x/l, v.y/l}; }
static build_vec3 build_normalize3(build_vec3 v) { double l = build_length3(v); return (build_vec3){v.x/l, v.y/l, v.z/l}; }
static build_vec4 build_normalize4(build_vec4 v) { double l = build_length4(v); return (build_vec4){v.x/l, v.y/l, v.z/l, v.w/l}; }

// Cross product (vec3 only)
static build_vec3 build_cross(build_vec3 a, build_vec3 b) {
    return (build_vec3){a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x};
}

// Reflect
static build_vec3 build_reflect3(build_vec3 v, build_vec3 n) {
    double d = build_dot3(v, n);
    return (build_vec3){v.x - 2.0*d*n.x, v.y - 2.0*d*n.y, v.z - 2.0*d*n.z};
}

// Lerp
static build_vec2 build_lerp2(build_vec2 a, build_vec2 b, double t) {
    return (build_vec2){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t};
}
static build_vec3 build_lerp3(build_vec3 a, build_vec3 b, double t) {
    return (build_vec3){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t};
}
static build_vec4 build_lerp4(build_vec4 a, build_vec4 b, double t) {
    return (build_vec4){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t, a.w + (b.w-a.w)*t};
}

// Vec2 arithmetic
static build_vec2 build_vec2_add(build_vec2 a, build_vec2 b) { return (build_vec2){a.x+b.x, a.y+b.y}; }
static build_vec2 build_vec2_sub(build_vec2 a, build_vec2 b) { return (build_vec2){a.x-b.x, a.y-b.y}; }
static build_vec2 build_vec2_mul(build_vec2 a, build_vec2 b) { return (build_vec2){a.x*b.x, a.y*b.y}; }
static build_vec2 build_vec2_scale(build_vec2 v, double s) { return (build_vec2){v.x*s, v.y*s}; }
static build_vec2 build_vec2_neg(build_vec2 v) { return (build_vec2){-v.x, -v.y}; }

// Vec3 arithmetic
static build_vec3 build_vec3_add(build_vec3 a, build_vec3 b) { return (build_vec3){a.x+b.x, a.y+b.y, a.z+b.z}; }
static build_vec3 build_vec3_sub(build_vec3 a, build_vec3 b) { return (build_vec3){a.x-b.x, a.y-b.y, a.z-b.z}; }
static build_vec3 build_vec3_mul(build_vec3 a, build_vec3 b) { return (build_vec3){a.x*b.x, a.y*b.y, a.z*b.z}; }
static build_vec3 build_vec3_scale(build_vec3 v, double s) { return (build_vec3){v.x*s, v.y*s, v.z*s}; }
static build_vec3 build_vec3_neg(build_vec3 v) { return (build_vec3){-v.x, -v.y, -v.z}; }

// Vec4 arithmetic
static build_vec4 build_vec4_add(build_vec4 a, build_vec4 b) { return (build_vec4){a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w}; }
static build_vec4 build_vec4_sub(build_vec4 a, build_vec4 b) { return (build_vec4){a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w}; }
static build_vec4 build_vec4_mul(build_vec4 a, build_vec4 b) { return (build_vec4){a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w}; }
static build_vec4 build_vec4_scale(build_vec4 v, double s) { return (build_vec4){v.x*s, v.y*s, v.z*s, v.w*s}; }
static build_vec4 build_vec4_neg(build_vec4 v) { return (build_vec4){-v.x, -v.y, -v.z, -v.w}; }

// --- Mat4 operations ---

static build_mat4 build_mat4_identity(void) {
    build_mat4 m = {{{1,0,0,0},{0,1,0,0},{0,0,1,0},{0,0,0,1}}};
    return m;
}

static build_mat4 build_mat4_mul(build_mat4 a, build_mat4 b) {
    build_mat4 r = {{{0}}};
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            for (int k = 0; k < 4; k++)
                r.m[i][j] += a.m[i][k] * b.m[k][j];
    return r;
}

static build_vec4 build_mat4_mul_vec4(build_mat4 m, build_vec4 v) {
    return (build_vec4){
        m.m[0][0]*v.x + m.m[0][1]*v.y + m.m[0][2]*v.z + m.m[0][3]*v.w,
        m.m[1][0]*v.x + m.m[1][1]*v.y + m.m[1][2]*v.z + m.m[1][3]*v.w,
        m.m[2][0]*v.x + m.m[2][1]*v.y + m.m[2][2]*v.z + m.m[2][3]*v.w,
        m.m[3][0]*v.x + m.m[3][1]*v.y + m.m[3][2]*v.z + m.m[3][3]*v.w
    };
}

static build_mat4 build_mat4_translate(build_vec3 t) {
    build_mat4 m = build_mat4_identity();
    m.m[0][3] = t.x; m.m[1][3] = t.y; m.m[2][3] = t.z;
    return m;
}

static build_mat4 build_mat4_scale(build_vec3 s) {
    build_mat4 m = {{{s.x,0,0,0},{0,s.y,0,0},{0,0,s.z,0},{0,0,0,1}}};
    return m;
}

static build_mat4 build_mat4_perspective(double fov, double aspect, double near_val, double far_val) {
    double f = 1.0 / tan(fov * 0.5);
    build_mat4 m = {{{0}}};
    m.m[0][0] = f / aspect;
    m.m[1][1] = f;
    m.m[2][2] = (far_val + near_val) / (near_val - far_val);
    m.m[2][3] = (2.0 * far_val * near_val) / (near_val - far_val);
    m.m[3][2] = -1.0;
    return m;
}

// --- Shader math functions ---

static double build_clampf(double x, double lo, double hi) { return x < lo ? lo : (x > hi ? hi : x); }
static build_vec3 build_clamp3(build_vec3 v, double lo, double hi) {
    return (build_vec3){build_clampf(v.x, lo, hi), build_clampf(v.y, lo, hi), build_clampf(v.z, lo, hi)};
}
static double build_smoothstep(double edge0, double edge1, double x) {
    double t = build_clampf((x - edge0) / (edge1 - edge0), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}
static double build_mix(double a, double b, double t) { return a + (b - a) * t; }
static double build_fract(double x) { return x - floor(x); }
static double build_step(double edge, double x) { return x < edge ? 0.0 : 1.0; }

// --- Effect handler runtime (setjmp/longjmp based) ---

#include <setjmp.h>

// Effect handler stack
typedef struct BuildHandler {
    jmp_buf env;
    int32_t effect_id;
    void* handler_data;
    struct BuildHandler* parent;
} BuildHandler;

// Global handler stack
static BuildHandler* __build_handler_stack = NULL;

// Push a handler onto the stack
static void build_push_handler(BuildHandler* h, int32_t effect_id) {
    h->effect_id = effect_id;
    h->handler_data = NULL;
    h->parent = __build_handler_stack;
    __build_handler_stack = h;
}

// Pop a handler from the stack
static void build_pop_handler(void) {
    if (__build_handler_stack) {
        __build_handler_stack = __build_handler_stack->parent;
    }
}

// Perform an effect operation - jumps to the nearest handler
static void build_perform(int32_t effect_id, int32_t op_id, void* arg, void* result) {
    BuildHandler* h = __build_handler_stack;
    while (h) {
        if (h->effect_id == effect_id) {
            h->handler_data = arg;
            longjmp(h->env, op_id + 1); // +1 because setjmp returns 0 on first call
        }
        h = h->parent;
    }
    // Unhandled effect - abort
    fprintf(stderr, "Unhandled effect %d operation %d\n", effect_id, op_id);
    abort();
}

// --- File I/O ---

static BuildString build_read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return build_string_new("");
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    BuildString qs;
    qs.ptr = buf;
    qs.len = (size_t)len;
    qs.cap = (size_t)(len + 1);
    return qs;
}

static bool build_write_file(const char* path, const char* content) {
    FILE* f = fopen(path, "wb");
    if (!f) return false;
    size_t len = strlen(content);
    size_t written = fwrite(content, 1, len, f);
    fclose(f);
    return written == len;
}

static bool build_file_exists(const char* path) {
    FILE* f = fopen(path, "rb");
    if (f) { fclose(f); return true; }
    return false;
}

// --- Process / Environment ---

static int32_t build_exit(int32_t code) {
    exit(code);
    return code; // unreachable
}

// --- Graphics Stub (Vulkan helper) ---
// Minimal stub that prints what a real Vulkan backend would do.
// Used for testing the FFI integration pattern.
// When connected to a real Vulkan backend, these are replaced by
// linking against vulkan_helper.c / the Vulkan SDK.

typedef struct {
    int32_t initialized;
    int32_t width;
    int32_t height;
    int32_t frame_count;
    int32_t should_close;
} BuildGfxContext;

static BuildGfxContext __build_gfx_ctx = {0, 0, 0, 0, 0};

static int32_t build_gfx_init(int32_t width, int32_t height, const char* title) {
    printf("[GFX] Initializing %dx%d window: %s\n", width, height, title);
    __build_gfx_ctx.initialized = 1;
    __build_gfx_ctx.width = width;
    __build_gfx_ctx.height = height;
    __build_gfx_ctx.frame_count = 0;
    __build_gfx_ctx.should_close = 0;
    printf("[GFX] Vulkan instance created\n");
    printf("[GFX] Physical device selected\n");
    printf("[GFX] Logical device created\n");
    printf("[GFX] Swapchain created (%dx%d)\n", width, height);
    return 1;
}

static int32_t build_gfx_load_shader(const char* path, int32_t stage) {
    printf("[GFX] Loading shader: %s (stage=%s)\n", path, stage == 0 ? "vertex" : "fragment");
    return 1;
}

static int32_t build_gfx_create_pipeline(int32_t vertex_shader, int32_t fragment_shader) {
    printf("[GFX] Creating graphics pipeline (vs=%d, fs=%d)\n", vertex_shader, fragment_shader);
    return 1;
}

static void build_gfx_begin_frame(void) {
    __build_gfx_ctx.frame_count++;
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Begin frame %d\n", __build_gfx_ctx.frame_count);
    }
}

static void build_gfx_clear(float r, float g, float b, float a) {
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Clear (%.1f, %.1f, %.1f, %.1f)\n", r, g, b, a);
    }
}

static void build_gfx_draw(int32_t vertex_count) {
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Draw %d vertices\n", vertex_count);
    }
}

static void build_gfx_end_frame(void) {
    if (__build_gfx_ctx.frame_count <= 3) {
        printf("[GFX] End frame %d\n", __build_gfx_ctx.frame_count);
    }
    if (__build_gfx_ctx.frame_count >= 3) {
        __build_gfx_ctx.should_close = 1;
    }
}

static int32_t build_gfx_should_close(void) {
    return __build_gfx_ctx.should_close;
}

static void build_gfx_shutdown(void) {
    printf("[GFX] Shutdown complete (%d frames rendered)\n", __build_gfx_ctx.frame_count);
    __build_gfx_ctx.initialized = 0;
}

// ============================================================================
// End BuildLang Runtime
// ============================================================================

// Type definitions
// Forward declarations
build_vec4 main(int32_t vertex_id);

build_vec4 main(int32_t vertex_id) {
    build_vec4 _ret;
    bool _2;
    double _3;
    bool _4;
    double _5;
    double _6;
    double x;
    bool _8;
    double _9;
    double _10;
    double y;
    build_vec4 _12;

    _2 = (vertex_id == 0);
    if (_2) goto bb1; else goto bb2;
bb1:
    _3 = 0;
    goto bb3;
bb2:
    _4 = (vertex_id == 1);
    if (_4) goto bb4; else goto bb5;
bb3:
    x = _3;
    _8 = (vertex_id == 0);
    if (_8) goto bb7; else goto bb8;
bb4:
    _5 = 0.5;
    goto bb6;
bb5:
    _6 = (-0.5);
    _5 = _6;
    goto bb6;
bb6:
    _3 = _5;
    goto bb3;
bb7:
    _9 = (-0.5);
    _10 = _9;
    goto bb9;
bb8:
    _10 = 0.5;
    goto bb9;
bb9:
    y = _10;
    _12 = (build_vec4){ x, y, 0, 1 };
    return _12;
}

